# Office Automation Configuration

## Anthropic Skills Integration

### Document Skills Paths
xlsx_skill_path: "Code/anthropic-skills/document-skills/xlsx"
docx_skill_path: "Code/anthropic-skills/document-skills/docx"
pdf_skill_path: "Code/anthropic-skills/document-skills/pdf"
pptx_skill_path: "Code/anthropic-skills/document-skills/pptx"

### Skill Creator Path
skill_creator_path: "Code/anthropic-skills/skill-creator"

## Workflow Configuration

### Human-in-the-Loop Settings
require_approval_for:
  - excel_formula_changes
  - document_format_conversion
  - new_skill_creation
  - data_extraction_operations

auto_approve_for:
  - read_only_operations
  - validation_only_checks
  - metadata_extraction

### Audit Trail Settings
audit_retention_days: 90
artifact_compression: true
detailed_logging: true

### Validation Requirements
excel_validation:
  max_formula_errors: 0
  require_recalc: true
  validate_references: true

document_validation:
  check_file_integrity: true
  verify_output_format: true
  validate_content_structure: true

## File Organization

### Artifacts Directory Structure
artifacts/
├── operations/           # Active operations
│   ├── {operation_id}/
│   │   ├── input/        # Original files
│   │   ├── processing/   # Intermediate files
│   │   ├── output/       # Final results
│   │   └── audit.json    # Complete audit trail
├── approvals/           # Pending approvals
└── completed/           # Approved operations

### Data Directory
data_directory: "Data/"
test_files:
  - "Test_Excel_Recrutement_v3.0.xlsx"
  - "Test_Excel_Recrutement_v3.0_SOLVED_fixed.xlsx"
  - "Test_Excel_Recrutement_v3.0_SOLVED_fixed2.xlsx"
  - "Test_Excel_Recrutement_v3.0_Solved.xlsx"
  - "Test_Excel_Recrutement_v3.0_SOLVEDsecond.xlsx"
  - "Aitor- Patino (1).xlsx"

## Agent Configuration

### Excel Processing Agent
excel_agent:
  name: "Excel Processing Agent"
  capabilities:
    - formula_management
    - data_analysis
    - template_preservation
    - error_validation
  validation_script: "recalc.py"
  libreoffice_required: true

### Document Processing Agent
document_agent:
  name: "Document Processing Agent"
  capabilities:
    - format_conversion
    - data_extraction
    - template_processing
    - multi_format_support
  supported_formats:
    - xlsx
    - docx
    - pdf
    - pptx

### Skill Creator Agent
skill_creator_agent:
  name: "Skill Creator Agent"
  capabilities:
    - skill_creation
    - skill_extension
    - template_generation
    - validation_packaging
  init_script: "init_skill.py"
  package_script: "package_skill.py"

## Integration Settings

### Claude Integration
claude_model: "claude-3-5-sonnet-20241022"
max_tokens: 4096
temperature: 0.1

### Error Handling
error_handling:
  max_retries: 3
  fallback_to_manual: true
  backup_before_processing: true
  rollback_on_failure: true

### Performance Settings
performance:
  parallel_processing: false
  batch_size: 1
  timeout_seconds: 300
  memory_limit_mb: 1024

## Security and Compliance

### Data Protection
data_protection:
  encrypt_sensitive_data: true
  secure_deletion: true
  access_logging: true
  audit_trail_immutable: true

### Compliance Requirements
compliance:
  gdpr_compliant: true
  data_retention_policy: "90_days"
  user_consent_required: true
  data_anonymization: true

## Development Settings

### Debug Mode
debug_mode: false
verbose_logging: false
save_intermediate_files: true
test_mode: false

### Testing Configuration
testing:
  use_test_data: true
  mock_external_apis: false
  validate_all_outputs: true
  performance_monitoring: true
